#!/usr/bin/env bash
#This script is displaying the numbers from 1 to 20. It's display bad luck from China after the 4th loop, bad luck from Japan after the 9th loop and bad luck from Italy using the while loop with the case statement.
x=1
while [ $x -ne 21 ]
do 
	echo "$x"
case $x in 
     4)         echo "bad luck from China"
	     ;;
     9)	        echo "bad luck from Japan"
	     ;;
    17)         echo "bad luck from Italy"
	     ;;
esac
	((x++))
done
