#!/usr/bin/env bash
#This script display the content of the current directory in a list format. 

# shellcheck disable=SC2034

for file in *
do
	find . -mindepth 1 -type f -name "$file"  | cut -d "-" -f 2 
done
