#!/usr/bin/env bash
#This script help us know if the given file exist or not, and if it's a regular file, or if is empty or not.

FILE="school"

if [ -e "$FILE" ]; then 
	echo "$FILE file exists" 
    if [ -s "$FILE" ]; then 
		echo "$FILE file is not empty"
    else
        echo "$FILE file is empty"
    fi

    if [ -f "$FILE" ]; then
		    echo "$FILE is a regular file"
    fi
else 
    echo "$FILE file does not exist"
fi

