#!/usr/bin/env bash
#This script give us a list of currently running processes, for all user, including those which might not have a TTY, display in a user-oriented format with a process hierarchy.

ps -auxf
